# Languages to check
languages:
  - en
  - en_GB

# Directories/Files/Regular expressions to exclude
exclude:
  - Build
  - Constants.swift

# Rules to apply
rules:
  #- support_flat_case
  - support_one_line_comment
  - support_multi_line_comment
  #- ignore_capitalization
  #- ignore_swift_keywords

# Words/Regular expressions to ignore
ignore:
  - \b[a-zA-Z]+able\b # Codable, Hashable ... (In Comments)
  #- \b[0-9a-fA-F]{6}\b
  #- \bhttps?:\/\/[^\s]+\b
  #- ^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){2,}$
  - swifty
  - lhs
  - rhs
