# Languages to check
languages:
  - en
  #- en_GB

# Directories/Files/Regular expressions to exclude
exclude:
  - Build
  - Constants.swift

# Rules to apply
rules:
  #- support_flat_case
  - support_one_line_comment
  - support_multi_line_comment
  #- support_british_words
  #- ignore_capitalization
  #- ignore_swift_keywords
  #- ignore_other_words
  #- ignore_shortened_words
  #- ignore_lorem_ipsum
  #- ignore_html_tags
  #- ignore_urls

# Words/Regular expressions to ignore
ignore:
  #- \b[a-zA-Z]+able\b # Codable, Hashable ... (In Comments)
  #- \b[0-9a-fA-F]{6}\b
  #- \bhttps?:\/\/[^\s]+\b
  #- ^[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+){2,}$
  - swifty
