#!/bin/sh

output=$(swiftyspell check .)
count=$(echo "$output" | grep -c "may be misspelled")

if [ $count -gt 0 ]; then
  echo "Spelling errors found. Please fix them before committing (You can run 'swiftyspell fix .' to fix most of them)."
  exit 1
fi
